eternal-return:
  url: https://open-api.bser.io
  header: x-api-key
  key: 0MNrzofHia9gSPPLfk4CpK7J7GaLlhk8r1U6qnR3

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysqldb
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 100
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        default_batch_fetch_size: 10

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - profile
              - email
          kakao:
            client-name: kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - profile_image
              - account_email
          naver:
            client-name: naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            scope:
              - name
              - email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            user-name-attribute: id
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
  codec:
    max-in-memory-size: 10MB

logging:
  level:
    root: info

jwt:
  secret-key: ZXRlcm5hbC1yZXR1cm5ldGVybmFsLXJldHVybmV0ZXJuYWwtcmV0dXJuZXRlcm5hbC1yZXR1cm5ldGVybmFsLXJldHVybmV0ZXJuYWwtcmV0dXJuZXRlcm5hbC1yZXR1cm4=