eternal-return:
  url: https://open-api.bser.io
  header: x-api-key
  key: 080NPo2eXN4aleG7BnrqoAHAAMe3ETmaCfC440w8

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysqldb
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 100
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 500
    show-sql: true
  codec:
    max-in-memory-size: 10MB

logging:
  level:
    root: info
