spring:
  cloud:
    aws:
      region:
        static: ap-northeast-2
      s3:
        bucket: ch-blog-bucket
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}